### ISSUE TITLE
Vergina Channel

### ISSUE THREAD

**Issue by loxiaskd** [loxiaskd/GREECE.IPTV#1]
#EXTM3U
#EXTINF:0 tvg-country="GR" tvg-logo="https://www.orathess.gr/wp-content/uploads/2020/12/vergina-tv-logo.jpg" group-title="Ellada",1 2 3 tv
https://www.verginanews.gr/web-tv-2/

**Comment by loxiaskd** [comment]
> #EXTM3U
> #EXTINF:0 tvg-country="GR" tvg-logo="https://www.orathess.gr/wp-content/uploads/2020/12/vergina-tv-logo.jpg" group-title="Ellada",1 2 3 tv
> https://www.verginanews.gr/web-tv-2/

**Comment by Sphinxroot** [comment]
depending on your player 

https://www.twitch.tv/verginachannel

- Kodi Only

#EXTINF:-1 tvg-logo="" group-title="", (TWITCH) (C_N)
plugin://plugin.video.twitch/?mode=play&channel_name=verginachannel

#EXTINF:-1 tvg-logo="" group-title="", (STK)
plugin://plugin.video.sendtokodi/?https://www.twitch.tv/verginachannel

- Streamlinker

#EXTINF:-1 tvg-logo="" group-title="",
http://free.fullspeed.tv/iptv-query?streaming-ip=https://www.twitch.tv/verginachannel
